name: Replace M3U URL
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  replace_m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Sync Upstream Repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # 添加上游仓库的远程地址，这里以 "upstream" 命名
          git remote add upstream https://github.com/wuwentao/bj-unicom-iptv.git
          
          # 获取上游仓库的最新分支信息
          git fetch upstream
          
          # 合并上游仓库的分支到当前分支（这里假设为 master 分支）
          git checkout upstream/master -- bj-unicom-iptv.m3u
          
      - name: Replace M3U URLs
        run: |
          sed 's#^rtp://\(.*\)#http://192.168.31.1:4022/rtp/\1#' bj-unicom-iptv.m3u > bj-unicom-iptv-udpxy.m3u

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected."

      - name: Commit and Push Changes
        run: |
          git add bj-unicom-iptv.m3u

          # 如果有变更则执行提交和推送操作
          git diff --cached --exit-code || git commit -m "Replace M3U URLs" && git push
